### PR TITLE
Website redesign

### PR DESCRIPTION
**Pull request by varkaria**
From : https://docs.google.com/spreadsheets/d/1Z6EJiAjnQQtS8vqIb0Y8aKW1ULtL90luAeTCout_-Xc/edit#gid=0

Frontend is currently a disaster copied from multiple places, needs to be cleaned up; no more anime girls!!! looking for something clean & professional looking

### CODE REVIEW

**Comment by varkaria** [comment]
cmyui user but me add it lmao

**Comment by varkaria** [comment]
😳

**Comment by tsunyoku** [comment]
closing as there's a new branch based on this, which is ported ready for our gulag switch.

**Comment by cmyui** [comment]
We may be able to revive this - if I get some clarification over some things I can resolve the merge conflicts.

A bit confused why profile.js was deleted?

**Pull request merged**
