### PR TITLE
Remove the ability for Donor & Premium users to change their own flags

### PR DESCRIPTION
**Pull request by lenforiee**

### CODE REVIEW

**Comment by lenforiee** [comment]
I also replaced the common module to ours for consistency and also added check for supporter on username change

**Comment by tsunyoku** [comment]
> I also replaced the common module to ours for consistency and also added check for supporter on username change

in future please separate these into 2 prs thank youuuuuuu

**Review by tsunyoku — APPROVED** [review]

**Comment by lenforiee** [comment]
> > I also replaced the common module to ours for consistency and also added check for supporter on username change
> 
> in future please separate these into 2 prs thank youuuuuuu

yeah i just felt like this doesnt need separate pr but sure

**Comment by tsunyoku** [comment]
> > > I also replaced the common module to ours for consistency and also added check for supporter on username change
> > 
> > 
> > in future please separate these into 2 prs thank youuuuuuu
> 
> yeah i just felt like this doesnt need separate pr but sure

every. change. should. be. in. it's. own. pr.

:)

**Comment by lenforiee** [comment]
👍

**Pull request merged**
