### PR TITLE
Set user opacity to 50% if restricted on clan members list

### PR DESCRIPTION
**Pull request by 7ez**

### CODE REVIEW

**Comment by cmyui** [comment]
hmm.. i think we should probably be kicking clan members upon restriction?

would be nice if we had a single piece of code handling restrictions as well.. currently it's very duplicated. probably a thing for rabbitmq?

**Comment by cmyui** [comment]
also would need to handle disband or perhaps ownership transfers if we do that

**Comment by cmyui** [comment]
@osuAkatsuki/core-devs thoughts?

**Comment by cmyui** [comment]
i'll merge this for now anyways. thanks for the PR!

**Review by cmyui — APPROVED** [review]

**Comment by tsunyoku** [comment]
> hmm.. i think we should probably be kicking clan members upon restriction?
> 
> would be nice if we had a single piece of code handling restrictions as well.. currently it's very duplicated. probably a thing for rabbitmq?

yep, we should probably turn my first places handling ticket on JIRA into something more generic. we should have 2 rabbitmq services - one which processes restrictions, one which processes unrestrictions. this also stops the absolute cat and mouse game ripple has with redis

**Comment by cmyui** [comment]
i think one service to handle anything related to accounts is fine

**Comment by tsunyoku** [comment]
maybe, their flow is entirely separate tho so that’s kinda why i was thinking of splitting it but i don’t think it matters

**Pull request merged**
